"""Add named enums for PostgreSQL

Revision ID: 0253d9b65248
Revises: 
Create Date: 2025-08-05 16:07:43.084995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0253d9b65248'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phases', sa.Column('phase_manager_id', sa.Integer(), nullable=True))
    op.add_column('phases', sa.Column('assistant_manager_id', sa.Integer(), nullable=True))
    op.alter_column('phases', 'status',
               existing_type=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='phasestatus'),
               type_=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='phase_status_enum'),
               existing_nullable=True)
    op.create_foreign_key(None, 'phases', 'users', ['assistant_manager_id'], ['id'])
    op.create_foreign_key(None, 'phases', 'users', ['phase_manager_id'], ['id'])
    op.add_column('projects', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='projectstatus'),
               type_=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='project_status_enum'),
               existing_nullable=True)
    op.create_foreign_key(None, 'projects', 'users', ['manager_id'], ['id'])
    op.drop_column('projects', 'manager')
    op.add_column('tasks', sa.Column('due_date', sa.Date(), nullable=True))
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               type_=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='task_status_enum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='task_status_enum'),
               type_=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               existing_nullable=True)
    op.drop_column('tasks', 'due_date')
    op.add_column('projects', sa.Column('manager', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='project_status_enum'),
               type_=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='projectstatus'),
               existing_nullable=True)
    op.drop_column('projects', 'manager_id')
    op.drop_constraint(None, 'phases', type_='foreignkey')
    op.drop_constraint(None, 'phases', type_='foreignkey')
    op.alter_column('phases', 'status',
               existing_type=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='phase_status_enum'),
               type_=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='phasestatus'),
               existing_nullable=True)
    op.drop_column('phases', 'assistant_manager_id')
    op.drop_column('phases', 'phase_manager_id')
    # ### end Alembic commands ###
